// Service worker: caches the whole game so it runs offline once installed.
// Bump VERSION whenever you ship an update so phones fetch the new files.
const VERSION = 'bummer-v4.5.1';
const FILES = [
 "./",
 "index.html",
 "manifest.webmanifest",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-180.png",
 "js/core/config.js",
 "js/core/math.js",
 "js/core/canvas.js",
 "js/core/input.js",
 "js/core/tween.js",
 "js/audio/settings.js",
 "js/audio/engine.js",
 "js/audio/music.js",
 "js/audio/sfx.js",
 "js/audio/ambience.js",
 "js/audio/music_act2.js",
 "js/render/pixel.js",
 "js/render/particles.js",
 "js/render/camera.js",
 "js/render/lighting.js",
 "js/render/world_time_weather.js",
 "js/render/post.js",
 "js/ui/pixelfont.js",
 "js/ui/toolkit.js",
 "js/ui/overlays.js",
 "js/ui/dialog.js",
 "js/characters/materials.js",
 "js/characters/people.js",
 "js/characters/player.js",
 "js/characters/monsters.js",
 "js/characters/monsters_act2.js",
 "js/characters/monsters_fx.js",
 "js/render/style.js",
 "js/characters/anim.js",
 "js/characters/hero_hd.js",
 "js/render/topdown.js",
 "js/render/hd.js",
 "js/render/motes.js",
 "js/data/content.js",
 "js/data/content_act2.js",
 "js/state/save.js",
 "js/state/migrate.js",
 "js/state/hud.js",
 "js/systems/progression.js",
 "js/systems/companions.js",
 "js/world/worlds.js",
 "js/scenes/manager.js",
 "js/scenes/icons.js",
 "js/scenes/title.js",
 "js/scenes/intro.js",
 "js/scenes/creation.js",
 "js/village/village.js",
 "js/village/interiors.js",
 "js/overworld/map.js",
 "js/overworld/map3d.js",
 "js/overworld/map_act2.js",
 "js/overworld/road.js",
 "js/village/port.js",
 "js/combat/background.js",
 "js/combat/arena3d.js",
 "js/combat/arena3d_act2.js",
 "js/combat/core.js",
 "js/combat/actions.js",
 "js/combat/deaths.js",
 "js/combat/end.js",
 "js/combat/draw.js",
 "js/combat/act2.js",
 "js/combat/deaths_weapon.js",
 "js/scenes/ending.js",
 "js/scenes/act2_story.js",
 "js/scenes/gallery.js",
 "js/scenes/animlab.js",
 "js/data/travellers.js",
 "js/systems/travellers.js",
 "js/combat/boost.js",
 "js/combat/hud_min.js",
 "js/world/life.js",
 "js/core/mobile.js",
 "js/main.js"
];
self.addEventListener('install', e => { e.waitUntil(caches.open(VERSION).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(res => { const copy = res.clone(); caches.open(VERSION).then(c => c.put(e.request, copy)); return res; }).catch(() => caches.match('index.html'))));
});
